x-app: &app
  build: .
  env_file: .env
  volumes:
    - .:/myapp

services:
  rails:
    <<: *app
    container_name: rails
    entrypoint: ./run-rails.sh
    environment:
      VITE_RUBY_HOST: vite
    ports:
      - "3000:3000"
    depends_on:
      - db

  vite:
    <<: *app
    container_name: vite
    entrypoint: ./run-vite.sh
    environment:
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"

  db:
    image: mysql:8.0.31
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
