default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

local:
  <<: *default
  database: rails_template_local
  username: root
  password: secret
  host: db

test:
  <<: *default
  database: rails_template_test

development:
  <<: *default
  database: rails_template_dev

production:
  <<: *default
  database: rails_template_prd
